// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dsciasyioztoupvdmend.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzY2lhc3lpb3p0b3VwdmRtZW5kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MTU3NjAsImV4cCI6MjA1OTE5MTc2MH0.-NZyzyZ642o0ZZOKLOzzBKvPpeq7TU_0LsafRuA2lhc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);